In [1]:
import numpy as np
import pandas as pd

In [30]:
MAX_TWIST = 200*2*np.pi/60
desired_fibre_od = 500e-6
df = pd.DataFrame(columns=[r'Preform OD (mm)', 'Twist Rate (rad/m)', 'Feed Rate (mm per min)'])
df['Preform OD (mm)'] = np.kron(np.arange(6, 11), np.ones(8))
df['Twist Rate (rad/m)'] = np.kron(np.ones(len(np.arange(6, 11))), np.arange(200, 1000, 100))
df['Feed Rate (mm per min)'] = 60*1000*(MAX_TWIST*np.pi*(desired_fibre_od/2)**2)/(np.pi*(df['Preform OD (mm)']*1e-3/2)**2 * df['Twist Rate (rad/m)'])
display(df)

Preform OD (mm)  Twist Rate (rad/m)  Feed Rate (mm per min)
0               6.0               200.0               43.633231
1               6.0               300.0               29.088821
2               6.0               400.0               21.816616
3               6.0               500.0               17.453293
4               6.0               600.0               14.544410
5               6.0               700.0               12.466638
6               6.0               800.0               10.908308
7               6.0               900.0                9.696274
8               7.0               200.0               32.057068
9               7.0               300.0               21.371379
10              7.0               400.0               16.028534
11              7.0               500.0               12.822827
12              7.0               600.0               10.685689
13              7.0               700.0                9.159162
14              7.0               800.0                8.014267
15              7.0               900.0                7.123793
16              8.0               200.0               24.543693
17              8.0               300.0               16.362462
18              8.0               400.0               12.271846
19              8.0               500.0                9.817477
20              8.0               600.0                8.181231
21              8.0               700.0                7.012484
22              8.0               800.0                6.135923
23              8.0               900.0                5.454154
24              9.0               200.0               19.392547
25              9.0               300.0               12.928365
26              9.0               400.0                9.696274
27              9.0               500.0                7.757019
28              9.0               600.0                6.464182
29              9.0               700.0                5.540728
30              9.0               800.0                4.848137
31              9.0               900.0                4.309455
32             10.0               200.0               15.707963
33             10.0               300.0               10.471976
34             10.0               400.0                7.853982
35             10.0               500.0                6.283185
36             10.0               600.0                5.235988
37             10.0               700.0                4.487990
38             10.0               800.0                3.926991
39             10.0               900.0                3.490659

In [22]:
print(np.einsum('i,j->ij',np.arange(6, 11), np.ones(8)))
print(np.kron(np.arange(6, 11), np.ones(8)))

[[ 6.  6.  6.  6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.]
 [10. 10. 10. 10. 10. 10. 10. 10.]]
[ 6.  6.  6.  6.  6.  6.  6.  6.  7.  7.  7.  7.  7.  7.  7.  7.  8.  8.
  8.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9.  9.  9.  9. 10. 10. 10. 10.
 10. 10. 10. 10.]
